[project]
name = "diffusion-pretrained"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "diffusers>=0.36.0",
    "librosa>=0.11.0",
    "numpy>=2.3.5",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
]
